# Generated by Django 5.0.6 on 2024-06-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=200)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('photo', models.ImageField(upload_to='fotos/')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_empleado', models.CharField(choices=[('Dependiente', 'Dependiente'), ('Independiente', 'Independiente')], max_length=13)),
                ('nivel_riesgo', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=3)),
                ('dias_trabajados', models.IntegerField(default=0, null=True)),
                ('horas_semanales', models.IntegerField(default=0)),
                ('hExtraDiurna', models.IntegerField(default=0)),
                ('hExtraNocturna', models.IntegerField(default=0)),
                ('hExtraDDominical', models.IntegerField(default=0)),
                ('hExtraNDominical', models.IntegerField(default=0)),
                ('hRecargoDominical', models.IntegerField(default=0)),
                ('hRecargoNDominical', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
