# Generated by Django 5.0.6 on 2024-06-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.IntegerField()),
                ('ficha', models.IntegerField()),
                ('programa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50)),
                ('photo', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
